export enum SaleStatus {
  PENDENTE = 'PENDENTE',
  CONFIRMADO = 'CONFIRMADO',
  A_SEPARAR = 'A_SEPARAR',
  SEPARADO = 'SEPARADO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
  PAGO_PARCIALMENTE = 'PAGO_PARCIALMENTE',
}
